version: '3.9'

services:
  user_api:
    build: .
    container_name: user_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=user_db
      - DB_PORT=5432
    env_file:
      - .env
  user_db:
    image: postgres:16.2-alpine
    container_name: user_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432

volumes:
  pgdata:
