#ktor:
#  development: true
#  deployment:
#    port: 8080
#  application:
#    modules:
#      - databaseDi
#      - userDi
    
#storage:
  DB_HOST: "$DB_HOST:localhost"
  DB_PORT: "$DB_PORT:5433"
  DB_NAME: "$DB_NAME:test"
  DB_USER: "$DB_USER:test"
  DB_PASS: "$DB_PASS:test"