ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - io.memorix.Application.module
    
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: ["jdbc:postgresql://", $DB_HOST, ":", $DB_PORT, "/", $DB_NAME, "?sslmode=disable"]
  user: $DB_USER
  password: $DB_PASS